---
name: auto_create_cluster_management_project
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/23946
rollout_issue_url: 
milestone: '12.10'
type: development
group: group::configure
default_enabled: false
