---
name: ci_auto_cancel_all_pipelines
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/46686
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/275997
milestone: '13.6'
type: development
group: group::pipeline authoring
default_enabled: true
