---
name: ci_artifacts_exclude
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/30708
rollout_issue_url: 
milestone: '13.0'
type: development
group: group::continuous integration
default_enabled: true
