---
name: ci_build_metadata_config
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/7238
rollout_issue_url: 
milestone: '11.7'
type: development
group: group::continuous integration
default_enabled: false
