---
name: ci_pipeline_editor_page
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/46580
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/270059
milestone: '13.6'
type: development
group: group::pipeline authoring
default_enabled: false
