---
name: ci_pipeline_latest
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/34160
rollout_issue_url: 
milestone: '13.2'
type: development
group: group::continuous integration
default_enabled: true
