---
name: ci_pipeline_status_omit_commit_sha_in_cache_key
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/33712
rollout_issue_url: 
milestone: '13.2'
type: development
group: group::continuous integration
default_enabled: true
