---
name: ci_rules_variables
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/48752
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/289803
milestone: '13.7'
type: development
group: group::pipeline authoring
default_enabled: false
