---
name: ci_store_pipeline_messages
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/33762
rollout_issue_url: 
milestone: '13.2'
type: development
group: group::continuous integration
default_enabled: true
