---
name: consolidated_edit_button
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/44311
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/270433
group: group::editor
type: development
default_enabled: false
