---
name: datadog_ci_integration
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/46564
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/284088
type: development
group: group::ecosystem
default_enabled: false
