---
name: deploy_tokens_api
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/25219
rollout_issue_url: 
milestone: '12.9'
type: development
group: group::package
default_enabled: true
