---
name: feature_flag_api
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/18198
rollout_issue_url: 
milestone: '12.4'
type: development
group: group::progressive delivery
default_enabled: false
