---
name: graphql_milestone_stats
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/35066
rollout_issue_url: 
milestone: '13.2'
type: development
group: group::release management
default_enabled: true
