---
name: include_lfs_blobs_in_archive
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/44116
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/268409
milestone: '13.5'
type: development
group: group::source code
default_enabled: true
