---
name: merge_orchestration_service
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/28532
rollout_issue_url: 
milestone: '12.10'
type: development
group: group::continuous integration
default_enabled: true
