---
name: merge_request_widget_graphql
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/38311
rollout_issue_url: 
milestone: '13.3'
type: development
group: group::code review
default_enabled: false
