---
name: multiple_todos
introduced_by_url: 
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/28355
milestone: '13.6'
type: development
group: group::project management
default_enabled: false
