---
name: new_pipeline_form_prefilled_vars
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/44120
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/263276
type: development
group: group::continuous integration
default_enabled: false
