---
name: release_mr_issue_urls
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/18727
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/276619
milestone: '12.4'
type: development
group: group::release management
default_enabled: true
