---
name: remove_resolve_note
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/45549
rollout_issue_url: 
milestone: '13.6'
type: development
group: group::source code
default_enabled: true
