---
name: show_inherited_labels
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/42960
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/267547
group: group::project management
type: development
default_enabled: true
