---
name: squash_options
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/33930
rollout_issue_url: 
milestone: '13.2'
type: development
group: group::source code
default_enabled: true
