---
name: track_unique_visits
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/33146
rollout_issue_url: 
milestone: '13.2'
type: development
group: group::analytics
default_enabled: true
