---
name: usage_data_incident_management_alerts_total_unique_counts
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/48087
rollout_issue_url:
milestone: '13.7'
type: development
group: group::monitor
default_enabled: false
