---
name: usage_data_i_code_review_viewed_diffs_file_by_file
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/48470
rollout_issue_url:
milestone: '13.7'
type: development
group: group::code review
default_enabled: true
