---
name: usage_data_incident_management_incident_change_confidential
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/40475
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/229918
milestone: '13.4'
type: development
group: group::health
default_enabled: true
