---
name: view_diffs_file_by_file
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/35223
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/229848
milestone: '13.2'
type: development
group: group::code review
default_enabled: true
