---
name: vue_issue_header
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/44440
rollout_issue_url:
milestone: '13.6'
type: development
group: group::project management
default_enabled: true
