---
name: analytics_similarity_search
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/37700
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/38675
group: group::analytics
type: development
default_enabled: true
