---
name: anonymous_visual_review_feedback
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/18710
rollout_issue_url: 
milestone: '12.5'
type: development
group: group::testing
default_enabled: false
