---
name: async_filtering
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/36421
rollout_issue_url: 
milestone: '13.3'
type: development
group: group::portfolio management
default_enabled: false
