---
name: audit_log_export_csv
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/31191
rollout_issue_url: 
milestone: '13.4'
type: development
group: group::compliance
default_enabled: false
