---
name: buy_storage_link
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/35360
rollout_issue_url: 
milestone: '13.2'
type: development
group: group::fulfillment
default_enabled: false
