---
name: convert_user_to_group_managed_accounts
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/24329
rollout_issue_url: 
milestone: '12.9'
type: development
group: group::access
default_enabled: false
