---
name: create_approval_todos_on_mr_update
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/26077
rollout_issue_url: 
milestone: '12.9'
type: development
group: group::source code
default_enabled: true
