---
name: enforced_sso_expiry
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/29786
rollout_issue_url: 
milestone: '13.0'
type: development
group: group::access
default_enabled: false
