---
name: geo_repository_reverification
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/8550
rollout_issue_url: 
milestone: '11.6'
type: development
group: group::geo
default_enabled: true
