---
name: geo_package_file_replication
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/37112
rollout_issue_url: 
milestone: '13.3'
type: development
group: group::geo
default_enabled: true
