---
name: geo_repository_verification
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/4428
rollout_issue_url: 
milestone: '10.6'
type: development
group: group::geo
default_enabled: true
