---
name: geo_self_service_framework
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/24498
rollout_issue_url: 
milestone: '12.8'
type: development
group: group::geo
default_enabled: false
