---
name: gitlab_employee_badge
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/issues/212259
rollout_issue_url: 
milestone: '13.0'
type: development
group: group::access
default_enabled: false
