---
name: group_coverage_data_report_graph
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/46698
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/276003
milestone: '13.6'
type: development
group: group::testing
default_enabled: false
