---
name: group_level_release_statistics
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/47245
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/283962
milestone: '13.6'
type: development
group: group::release
default_enabled: true
