---
name: missing_mr_security_scan_types
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/40171
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/241154
milestone: '13.4'
type: development
group: group::threat insights
default_enabled: false
