---
name: new_issues_analytics_chart_data
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/46444
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/247271
group: group::analytics
type: development
default_enabled: false
