---
name: pull_mirror_branch_prefix
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/17368
rollout_issue_url: 
milestone: '12.4'
type: development
group: group::source code
default_enabled: false
