---
name: sign_up_on_sso
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/10338
rollout_issue_url: 
milestone: '12.0'
type: development
group: manage::access
default_enabled: false
