---
name: update_target_approvers
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/38575
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/238977
group: group:source code
type: development
default_enabled: false
