---
name: value_stream_analytics_path_navigation
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/31069
rollout_issue_url: 
milestone: '13.0'
type: development
group: group::analytics
default_enabled: false
