---
name: ci_trace_overwrite
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/41304
rollout_issue_url: 
milestone: '13.4'
type: ops
group: group::continuous integration
default_enabled: false
